from pathlib import Path
import io, json, zipfile
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from engine import DATES, MINIMUM, STORMS, load_history, simulate, process_inbox, compare_responses

st.set_page_config(page_title='The Treasury Team of One',page_icon='◈',layout='wide',initial_sidebar_state='expanded')
BASE=Path(__file__).parent
def first_existing(*paths): return next((p for p in paths if p.exists()),paths[0])
SAMPLE=first_existing(BASE/'data'/'historical_forecast_errors.csv',BASE/'historical_forecast_errors.csv')
INBOX=first_existing(BASE/'data'/'monday_inbox',BASE)
INBOX_JSON=first_existing(BASE/'data'/'inbox.json',BASE/'inbox.json')
C={'navy':'#081F33','cyan':'#00BAC6','amber':'#F4AB00','red':'#D63F42','green':'#15836D','bg':'#EDF3F7'}

st.markdown(f'''<style>
header[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],#MainMenu{{display:none!important}}.stApp{{background:{C['bg']}}}.block-container{{padding:1rem 1.05rem .9rem;max-width:1550px}}[data-testid="stSidebar"]{{background:#081F33}}[data-testid="stSidebar"] p,[data-testid="stSidebar"] h1,[data-testid="stSidebar"] h2,[data-testid="stSidebar"] h3,[data-testid="stSidebar"] label{{color:#F1F7FA!important}}
.hero{{background:linear-gradient(120deg,#081F33,#145E7C);color:white;border-radius:14px;padding:.64rem .95rem;margin-bottom:.4rem}}.hero h1{{font-size:1.48rem;margin:.06rem 0}}.hero p{{font-size:.82rem;color:#D8E8EF;margin:0}}.eyebrow{{font-size:.6rem;letter-spacing:.12em;color:#43E6ED;font-weight:800;text-transform:uppercase}}.panel{{background:white;border:1px solid #D5E1E8;border-radius:12px;padding:.68rem .8rem;box-shadow:0 3px 10px rgba(8,31,51,.06)}}.row{{display:flex;gap:.45rem;align-items:center;border-bottom:1px solid #E7EEF2;padding:.32rem 0;font-size:.81rem}}.grow{{flex:1}}.muted{{font-size:.73rem;color:#687C8E}}.badge{{font-size:.61rem;font-weight:800;border-radius:999px;padding:.1rem .38rem;background:#DFF7F7;color:#087680}}.warn{{background:#FFF7E3;border-left:4px solid #F4AB00;padding:.48rem .65rem;border-radius:9px;font-size:.8rem}}.danger{{background:#FFF0F0;border-left:4px solid #D63F42;padding:.48rem .65rem;border-radius:9px;font-size:.8rem}}.success{{background:#EAF8F4;border-left:4px solid #15836D;padding:.48rem .65rem;border-radius:9px;font-size:.8rem}}
div[data-testid="stMetric"]{{background:white;border:1px solid #D5E1E8;border-radius:11px;padding:.36rem .56rem}}div[data-testid="stMetricLabel"]{{font-size:.68rem}}div[data-testid="stMetricValue"]{{font-size:1.16rem}}.stButton>button{{min-height:34px;border-radius:9px;font-weight:800}}.stButton>button[kind="primary"]{{background:#00A6B2!important;border-color:#00A6B2!important;color:#fff!important}}[data-testid="stSidebar"] .stButton>button{{background:#F8FAFC!important;color:#17324A!important}}[data-testid="stSidebar"] .stButton>button p{{color:#17324A!important}}
.clockbar{{display:grid;grid-template-columns:150px minmax(260px,1fr) 150px;align-items:center;gap:.85rem;background:#0B2C43;border:1px solid #164D68;border-radius:11px;padding:.48rem .75rem;margin:0 0 .48rem}}.clocktime{{font-size:1rem;font-weight:900;color:#fff}}.clocklabel{{font-size:.66rem;letter-spacing:.08em;text-transform:uppercase;color:#D7E7EF;font-weight:900}}.clocktrack{{height:7px;background:#315266;border-radius:999px;overflow:hidden}}.clockfill{{height:100%;background:linear-gradient(90deg,#35D8DE,#F4AB00,#FF6467)}}.clockremain{{font-size:.78rem;font-weight:900;color:#FF8B8D;text-align:right}}
.titlehero{{position:relative;min-height:calc(100vh - 205px);overflow:hidden;display:grid;grid-template-columns:1.62fr .78fr;align-items:center;gap:1.6rem;background:linear-gradient(135deg,#061C2D 0%,#0B3E59 58%,#086B78 100%);color:white;border-radius:24px;padding:2.7rem 3rem;box-shadow:0 20px 48px rgba(8,31,51,.24)}}.titlehero:before{{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:38px 38px}}.titlecopy{{position:relative;z-index:2}}.titlehero h1{{font-size:clamp(2.45rem,3.15vw,3.35rem);line-height:1;margin:.45rem 0 .65rem;white-space:nowrap;letter-spacing:-.035em}}.titlehero h2{{font-size:1.42rem;color:#D9EDF2;margin:0 0 .8rem}}.titlehero p{{color:#C5DCE5;font-size:1.03rem}}.titlemeta{{font-size:.83rem;color:#C6DAE3;margin-top:1.35rem}}.casebadge{{display:inline-block;border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.09);border-radius:999px;padding:.35rem .68rem;margin:.16rem;font-size:.76rem;font-weight:800}}.deadlinebadge{{border-color:#F4C24F;background:rgba(244,171,0,.2);color:#FFE49A}}.openingquestion{{margin:.75rem 0 .45rem;text-align:center;color:#17324A;font-weight:900;font-size:1rem}}
.agentvisual{{position:relative;z-index:2;height:330px;display:flex;align-items:center;justify-content:center}}.agentcore{{position:relative;width:138px;height:138px;border-radius:50%;display:flex;align-items:center;justify-content:center;text-align:center;background:radial-gradient(circle at 35% 30%,#42E4ED,#008B99 62%,#005A67);box-shadow:0 0 0 14px rgba(66,228,237,.08),0 0 0 30px rgba(66,228,237,.045);font-size:.8rem;font-weight:900;animation:corePulse 2.8s ease-in-out infinite}}.agentorbit{{position:absolute;width:292px;height:292px;border:1px solid rgba(129,235,241,.35);border-radius:50%;animation:orbitSpin 26s linear infinite}}.agentnode{{position:absolute;width:90px;padding:.42rem .35rem;border-radius:10px;background:rgba(4,29,45,.9);border:1px solid rgba(104,226,234,.42);font-size:.64rem;text-align:center;font-weight:800;animation:counterSpin 26s linear infinite}}.source-agent{{border-top:3px solid #4AA8FF}}.transform-agent{{border-top:3px solid #35D8DE}}.risk-agent{{border-top:3px solid #F4AB00}}.control-agent{{border-top:3px solid #FF777A}}.n1{{top:0;left:101px}}.n2{{top:64px;right:-18px}}.n3{{bottom:54px;right:-12px}}.n4{{bottom:-4px;left:101px}}.n5{{bottom:54px;left:-12px}}.n6{{top:64px;left:-18px}}.dataorb{{position:absolute;left:50%;top:50%;border-radius:50%;z-index:5;offset-rotate:0deg;filter:drop-shadow(0 0 7px currentColor)}}.dataorb:after{{content:'';position:absolute;inset:-5px;border-radius:50%;border:1px solid currentColor;opacity:.25}}.orb1{{width:11px;height:11px;color:#FFE08A;background:#FFE08A;offset-path:path('M 0,-142 A 142,142 0 1,1 -1,-142');animation:dataOrbit 7.5s linear infinite}}.orb2{{width:8px;height:8px;color:#56ECF2;background:#56ECF2;offset-path:path('M 0,-112 A 112,112 0 1,0 -1,-112');animation:dataOrbit 5.8s linear infinite reverse}}.orb3{{width:14px;height:14px;color:#70AFFF;background:#70AFFF;offset-path:path('M 0,-156 A 156,156 0 1,1 -1,-156');animation:dataOrbit 11s linear infinite;animation-delay:-4s}}.orb4{{width:7px;height:7px;color:#FF8B8D;background:#FF8B8D;offset-path:path('M 0,-92 A 92,92 0 1,0 -1,-92');animation:dataOrbit 4.7s linear infinite;animation-delay:-1.5s}}.orb5{{width:9px;height:9px;color:#B2F7C8;background:#B2F7C8;offset-path:path('M 0,-130 A 130,130 0 1,1 -1,-130');animation:dataOrbit 8.8s linear infinite;animation-delay:-6s}}@keyframes orbitSpin{{to{{transform:rotate(360deg)}}}}@keyframes counterSpin{{to{{transform:rotate(-360deg)}}}}@keyframes corePulse{{50%{{transform:scale(1.035)}}}}@keyframes dataOrbit{{to{{offset-distance:100%}}}}@media(prefers-reduced-motion:reduce){{.agentcore,.agentorbit,.agentnode,.dataorb{{animation:none!important}}}}
.thesisstage{{display:grid;grid-template-columns:1fr 90px 1.1fr 90px 1fr;align-items:center;gap:.45rem;margin:.65rem 0}}.thesiscol{{background:white;border:1px solid #D5E1E8;border-radius:14px;padding:.8rem;min-height:250px}}.thesisitem{{display:flex;align-items:center;gap:.55rem;padding:.48rem .55rem;border-bottom:1px solid #E7EEF2;font-size:.82rem}}.thesisicon{{width:28px;height:28px;border-radius:8px;display:flex;align-items:center;justify-content:center;background:#E8F7F8;color:#087F89;font-weight:900}}.thesisarrow{{text-align:center;color:#00A6B2;font-size:2rem;font-weight:900}}.thesiscenter{{background:linear-gradient(145deg,#0B2C43,#11647B);color:white;border-radius:16px;padding:1rem;text-align:center;box-shadow:0 12px 28px rgba(8,31,51,.16)}}.thesiscenter .big{{font-size:1.22rem;font-weight:900;margin:.35rem 0}}.thesiscenter .small{{font-size:.76rem;color:#D4E8EF}}.thesisresult{{padding:.55rem;border-radius:10px;background:#EAF8F4;border-left:4px solid #15836D;margin:.45rem 0;font-size:.8rem}}
.orgnet{{position:relative;min-height:420px;background:radial-gradient(circle at 50% 50%,rgba(0,186,198,.12),transparent 27%),linear-gradient(135deg,#071F32,#0B5368);border-radius:18px;overflow:hidden;border:1px solid #1B6075}}.orgnet:before{{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:32px 32px}}.treasuryhub{{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:165px;height:165px;border-radius:50%;display:flex;align-items:center;justify-content:center;text-align:center;background:radial-gradient(circle at 35% 30%,#3CDCE5,#008A99 65%,#075A66);color:white;font-weight:900;box-shadow:0 0 0 18px rgba(60,220,229,.09),0 0 0 38px rgba(60,220,229,.05);z-index:3}}.entitynode{{position:absolute;width:180px;background:#F9FCFD;color:#17324A;border-radius:12px;padding:.55rem .65rem;box-shadow:0 8px 22px rgba(0,0,0,.22);z-index:3;border-left:4px solid #35D8DE}}.entitynode b{{font-size:.83rem}}.entitynode span{{display:block;font-size:.66rem;color:#657B8A;margin-top:.12rem}}.org1{{left:4%;top:8%}}.org2{{left:3%;top:39%}}.org3{{left:8%;bottom:7%}}.org4{{right:5%;top:8%;border-left-color:#F4AB00}}.org5{{right:3%;top:39%;border-left-color:#70AFFF}}.org6{{right:8%;bottom:7%;border-left-color:#70AFFF}}.flowline{{position:absolute;height:2px;background:linear-gradient(90deg,transparent,#50DDE5,#50DDE5);transform-origin:left center;opacity:.8;z-index:1}}.fl1{{left:20%;top:23%;width:31%;transform:rotate(25deg)}}.fl2{{left:19%;top:49%;width:32%}}.fl3{{left:22%;bottom:22%;width:31%;transform:rotate(-25deg)}}.fl4{{left:50%;top:50%;width:31%;transform:rotate(-25deg)}}.fl5{{left:50%;top:50%;width:32%}}.fl6{{left:50%;top:50%;width:31%;transform:rotate(25deg)}}.packet{{position:absolute;width:9px;height:9px;border-radius:50%;background:#FFE08A;box-shadow:0 0 12px #FFE08A;z-index:4;animation:packetMove 2.8s ease-in-out infinite}}.pk1{{left:25%;top:25%}}.pk2{{left:28%;top:48%;animation-delay:.8s}}.pk3{{right:27%;top:48%;animation-delay:1.5s}}@keyframes packetMove{{0%,100%{{opacity:.25;transform:scale(.7)}}50%{{opacity:1;transform:scale(1.35)}}}}
.pipeline{{display:grid;grid-template-columns:repeat(5,1fr);gap:.5rem}}.stagecard{{position:relative;background:white;border:1px solid #D5E1E8;border-radius:12px;padding:.65rem;min-height:128px}}.stagecard.complete{{border-top:4px solid #15836D}}.stagecard.ready{{border-top:4px solid #F4AB00;background:#FFF9EA}}.stagecard.waiting{{border-top:4px solid #B7C5CE;opacity:.72}}.stagestate{{display:inline-block;margin-top:.45rem;padding:.14rem .4rem;border-radius:999px;background:#EDF3F7;font-size:.62rem;font-weight:900}}.stagecard.complete .stagestate{{background:#EAF8F4;color:#08765F}}.stagecard.ready .stagestate{{background:#FFF0C2;color:#815900}}.actflow{{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin:.65rem 0}}.actnode{{background:white;border:1px solid #D5E1E8;border-radius:12px;padding:.65rem;text-align:center;font-size:.8rem;font-weight:800;color:#17324A}}@media(max-width:1250px){{.titlehero h1{{font-size:2.55rem}}}}@media(max-width:1100px){{.titlehero{{grid-template-columns:1fr;min-height:calc(100vh - 185px);padding:2rem}}.titlehero h1{{white-space:normal}}.agentvisual{{display:none}}}}

/* World-class thesis */
.storyboard{{display:grid;grid-template-columns:1fr 68px 1.14fr 68px 1fr;align-items:stretch;gap:.5rem;margin:.7rem 0}}.storypanel{{background:#fff;border:1px solid #d5e1e8;border-radius:16px;padding:1rem;box-shadow:0 8px 22px rgba(8,31,51,.07);min-height:330px}}.storypanel.problem{{border-top:5px solid #f4ab00}}.storypanel.output{{border-top:5px solid #15836d}}.storyarrow{{display:flex;align-items:center;justify-content:center;color:#00a6b2;font-size:2.25rem;font-weight:900}}.realitygrid{{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin:.7rem 0}}.realitymetric{{background:#f3f7fa;border-radius:11px;padding:.62rem;text-align:center}}.realitymetric strong{{display:block;font-size:1.35rem;color:#0b2c43}}.realitymetric span{{font-size:.68rem;color:#64798a}}.agentstack{{background:linear-gradient(145deg,#08283d,#0e6277);color:#fff;border-radius:16px;padding:1rem;box-shadow:0 14px 30px rgba(8,31,51,.18);min-height:330px}}.agentstep{{display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:.55rem;padding:.48rem .55rem;margin:.34rem 0;border:1px solid rgba(255,255,255,.16);border-radius:10px;background:rgba(255,255,255,.06)}}.agentstep .num{{width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#35d8de;color:#062637;font-size:.74rem;font-weight:900}}.agentstep b{{font-size:.78rem}}.agentstep small{{font-size:.62rem;color:#cfe5ec}}.humanbar{{margin-top:.65rem;padding:.62rem;border-radius:11px;border:1px solid rgba(255,224,138,.6);background:rgba(244,171,0,.12);text-align:center;font-size:.75rem}}.outputcard{{padding:.62rem .7rem;margin:.45rem 0;border-radius:11px;background:#eaf8f4;border-left:4px solid #15836d}}.outputcard b{{font-size:.78rem}}.outputcard span{{display:block;font-size:.67rem;color:#506d68;margin-top:.12rem}}
/* Organization exchange */
.orgboard{{display:grid;grid-template-columns:1fr 70px 1.08fr 70px 1fr;align-items:center;gap:.35rem;background:linear-gradient(135deg,#071f32,#0b5368);border-radius:18px;padding:1.05rem;min-height:450px;box-shadow:0 12px 30px rgba(8,31,51,.16)}}.orgstack{{display:flex;flex-direction:column;gap:.65rem}}.orgcard{{background:#f9fcfd;border-radius:13px;padding:.68rem .75rem;color:#17324a;box-shadow:0 7px 18px rgba(0,0,0,.18);border-left:4px solid #35d8de}}.orgcard.acquired{{border-left-color:#f4ab00}}.orgcard.international{{border-left-color:#70afff}}.orgcard b{{font-size:.82rem}}.orgcard .orgmeta{{font-size:.65rem;color:#60798a;margin:.18rem 0}}.filechip{{display:inline-block;font-size:.58rem;border-radius:999px;padding:.12rem .35rem;background:#e8f2f6;color:#315568;margin:.1rem .1rem 0 0}}.orgflow{{position:relative;height:100%;display:flex;align-items:center;justify-content:center}}.orgflow:before{{content:'';width:100%;height:2px;background:#48d7df}}.orgflow:after{{content:'›';position:absolute;right:2px;color:#ffe08a;font-size:2rem;font-weight:900}}.orgflow.reverse:after{{content:'‹';left:2px;right:auto}}.orgflow.reverse:before{{background:linear-gradient(90deg,#48d7df,#ffe08a)}}.hubcard{{position:relative;text-align:center;padding:1.25rem .85rem;border-radius:22px;color:#fff;background:radial-gradient(circle at 35% 28%,#3cdce5,#008a99 67%,#075a66);box-shadow:0 0 0 15px rgba(60,220,229,.09),0 16px 35px rgba(0,0,0,.25)}}.hubcard h3{{font-size:1.2rem!important;margin:.22rem 0!important}}.hubcard p{{font-size:.68rem;color:#d9f1f4}}.hubpulse{{position:absolute;inset:-18px;border:1px solid rgba(79,225,233,.4);border-radius:28px;animation:hubPulse 2.8s ease-in-out infinite}}@keyframes hubPulse{{50%{{transform:scale(1.035);opacity:.45}}}}.orgsummary{{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin-top:.6rem}}.summarytile{{background:#fff;border:1px solid #d5e1e8;border-radius:12px;padding:.58rem .68rem}}.summarytile strong{{display:block;font-size:1.12rem;color:#0b2c43}}.summarytile span{{font-size:.66rem;color:#64798a}}
/* Readable wrangling rail */
.processrail{{display:grid;grid-template-columns:repeat(5,1fr);gap:.45rem;margin:.5rem 0}}.processstep{{position:relative;border-radius:11px;padding:.55rem .55rem .5rem;background:#fff;border:1px solid #d5e1e8;min-height:88px}}.processstep:after{{content:'›';position:absolute;right:-.38rem;top:29px;color:#8db0bf;font-size:1.2rem;z-index:3}}.processstep:last-child:after{{display:none}}.processstep.complete{{border-top:4px solid #15836d}}.processstep.ready{{border-top:4px solid #f4ab00;background:#fff9e8}}.processstep.waiting{{border-top:4px solid #b7c5ce;opacity:.7}}.processstep b{{display:block;font-size:.74rem;line-height:1.1;margin:.1rem 0 .3rem}}.processstep small{{display:block;font-size:.61rem;line-height:1.25;color:#667c8b}}.statepill{{display:inline-block;margin-top:.35rem;border-radius:999px;padding:.11rem .34rem;font-size:.56rem;font-weight:900;background:#edf3f7}}.complete .statepill{{background:#eaf8f4;color:#08765f}}.ready .statepill{{background:#fff0c2;color:#815900}}.workbench{{display:grid;grid-template-columns:.92fr 1.25fr;gap:1rem;align-items:start}}.activework{{background:#fff;border:1px solid #d5e1e8;border-radius:14px;padding:.8rem;min-height:305px}}.activeagent{{font-size:1.15rem;font-weight:900;color:#17324a;margin:.25rem 0}}.checkrow{{padding:.42rem .48rem;border-bottom:1px solid #e7eef2;font-size:.72rem}}.checkrow span{{float:right;font-weight:900;color:#15836d}}@media(max-width:1200px){{.storyboard{{grid-template-columns:1fr 42px 1fr 42px 1fr}}.orgboard{{grid-template-columns:1fr 45px 1fr 45px 1fr}}.processstep small{{display:none}}}}@media(prefers-reduced-motion:reduce){{.hubpulse{{animation:none!important}}}}

/* World-class presentation system */
.execstory{{display:grid;grid-template-columns:.95fr 1.16fr .95fr;gap:1rem;align-items:stretch;margin:.7rem 0 .55rem}}.execpanel{{background:#fff;border:1px solid #d4e0e7;border-radius:18px;padding:1rem;box-shadow:0 8px 24px rgba(8,31,51,.08);min-height:340px}}.execpanel.problem{{border-top:5px solid #f4ab00}}.execpanel.result{{border-top:5px solid #15836d}}.execpanel h3{{font-size:1.25rem!important;line-height:1.16!important;margin:.42rem 0 .68rem!important}}.metricquad{{display:grid;grid-template-columns:1fr 1fr;gap:.48rem;margin:.6rem 0}}.metricbox{{background:#f3f7fa;border-radius:12px;padding:.58rem;text-align:center}}.metricbox strong{{display:block;font-size:1.42rem;color:#0b2c43}}.metricbox span{{font-size:.67rem;color:#64798a}}.friction{{display:grid;grid-template-columns:24px 1fr;gap:.42rem;align-items:center;padding:.42rem 0;border-bottom:1px solid #e7eef2;font-size:.71rem}}.friction i{{display:flex;width:22px;height:22px;border-radius:7px;align-items:center;justify-content:center;background:#fff0c2;color:#815900;font-style:normal;font-size:.62rem;font-weight:900}}
.workflowcore{{background:linear-gradient(155deg,#07283d,#0f647a);color:#fff;border-radius:20px;padding:1rem;box-shadow:0 16px 34px rgba(8,31,51,.2);min-height:340px;position:relative;overflow:hidden}}.workflowcore:before{{content:'';position:absolute;inset:0;background:radial-gradient(circle at 85% 5%,rgba(53,216,222,.2),transparent 34%)}}.workflowhead{{position:relative;text-align:center;margin-bottom:.5rem}}.workflowhead strong{{display:block;font-size:1.03rem;margin:.25rem 0}}.workflowrow{{position:relative;display:grid;grid-template-columns:34px 1fr 22px;align-items:center;gap:.52rem;padding:.5rem .58rem;margin:.36rem 0;border:1px solid rgba(255,255,255,.18);border-radius:11px;background:rgba(255,255,255,.07)}}.workflowrow .stepnum{{display:flex;width:30px;height:30px;border-radius:50%;align-items:center;justify-content:center;background:#35d8de;color:#062637;font-weight:900;font-size:.75rem}}.workflowrow b{{display:block;font-size:.78rem;line-height:1.1}}.workflowrow small{{display:block;font-size:.62rem;color:#cfe5ec;line-height:1.25;margin-top:.12rem}}.workflowrow .chev{{color:#ffe08a;font-size:1.1rem;font-weight:900}}.controlgate{{position:relative;margin-top:.6rem;padding:.62rem;border:1px solid rgba(255,224,138,.65);background:rgba(244,171,0,.14);border-radius:11px;text-align:center}}.controlgate b{{font-size:.72rem}}.controlgate span{{display:block;font-size:.61rem;color:#f7e9bd;margin-top:.12rem}}.resultitem{{padding:.58rem .68rem;margin:.46rem 0;border-radius:11px;background:#eaf8f4;border-left:4px solid #15836d}}.resultitem b{{display:block;font-size:.78rem}}.resultitem span{{display:block;font-size:.64rem;color:#53706b;margin-top:.12rem}}
.networkstage{{display:grid;grid-template-columns:1fr 115px .78fr 115px 1fr;align-items:center;gap:.35rem;background:linear-gradient(135deg,#071f32,#0b5368);border-radius:20px;padding:1.1rem;min-height:450px;box-shadow:0 14px 34px rgba(8,31,51,.18)}}.entitycolumn{{display:flex;flex-direction:column;gap:.62rem}}.entitycard{{background:#fbfdfe;color:#17324a;border-radius:13px;padding:.66rem .74rem;box-shadow:0 8px 20px rgba(0,0,0,.2);border-left:4px solid #35d8de}}.entitycard.acquired{{border-left-color:#f4ab00}}.entitycard.global{{border-left-color:#70afff}}.entitycard b{{font-size:.8rem}}.entitycard .meta{{font-size:.62rem;color:#60798a;margin:.15rem 0 .27rem}}.datachip{{display:inline-block;padding:.13rem .35rem;border-radius:999px;background:#e8f2f6;color:#315568;font-size:.55rem;margin:.08rem .08rem 0 0}}.lane{{position:relative;height:245px;overflow:hidden}}.lane:before{{content:'';position:absolute;left:0;right:0;top:50%;height:2px;background:linear-gradient(90deg,rgba(72,215,223,.2),#48d7df)}}.lane.inbound:after{{content:'›';position:absolute;right:0;top:calc(50% - 18px);font-size:2.1rem;color:#ffe08a}}.lane.outbound:before{{background:linear-gradient(90deg,#48d7df,rgba(72,215,223,.2))}}.lane.outbound:after{{content:'‹';position:absolute;left:0;top:calc(50% - 18px);font-size:2.1rem;color:#ffe08a}}.datapacket{{position:absolute;top:calc(50% - 6px);width:12px;height:12px;border-radius:50%;background:#ffe08a;box-shadow:0 0 14px #ffe08a;animation:packetRight 3.2s ease-in-out infinite}}.outbound .datapacket{{animation:packetLeft 3.2s ease-in-out infinite}}.p2{{animation-delay:1.05s!important}}.p3{{animation-delay:2.1s!important}}@keyframes packetRight{{0%{{left:2%;opacity:0}}15%{{opacity:1}}85%{{opacity:1}}100%{{left:90%;opacity:0}}}}@keyframes packetLeft{{0%{{right:2%;opacity:0}}15%{{opacity:1}}85%{{opacity:1}}100%{{right:90%;opacity:0}}}}.controlhub{{position:relative;text-align:center;color:#fff;border-radius:24px;padding:1.2rem .75rem;background:radial-gradient(circle at 35% 28%,#40dce5,#008a99 67%,#075a66);box-shadow:0 0 0 16px rgba(60,220,229,.1),0 0 0 34px rgba(60,220,229,.05),0 18px 38px rgba(0,0,0,.25)}}.controlhub .ring{{position:absolute;inset:-18px;border:1px solid rgba(82,228,235,.42);border-radius:30px;animation:ringbreath 2.8s ease-in-out infinite}}.controlhub strong{{display:block;font-size:1.02rem}}.controlhub span{{display:block;font-size:.62rem;color:#d9f1f4;margin-top:.34rem}}@keyframes ringbreath{{50%{{transform:scale(1.035);opacity:.45}}}}.netstats{{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin-top:.55rem}}.netstat{{background:#fff;border:1px solid #d5e1e8;border-radius:12px;padding:.5rem .64rem}}.netstat strong{{font-size:1.14rem;color:#0b2c43}}.netstat span{{display:block;font-size:.63rem;color:#64798a}}
.flowrail{{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.42rem;margin:.48rem 0 .65rem}}.flowstage{{position:relative;background:#fff;border:1px solid #d5e1e8;border-radius:12px;padding:.55rem;min-height:103px}}.flowstage:after{{content:'›';position:absolute;right:-.34rem;top:38px;color:#89aeba;font-size:1.15rem;z-index:3}}.flowstage:last-child:after{{display:none}}.flowstage.complete{{border-top:4px solid #15836d}}.flowstage.ready{{border-top:4px solid #f4ab00;background:#fff9e8}}.flowstage.waiting{{border-top:4px solid #b7c5ce;opacity:.68}}.flowstage b{{display:block;font-size:.71rem;line-height:1.1;margin:.12rem 0 .3rem;white-space:normal}}.flowstage small{{display:block;font-size:.59rem;line-height:1.25;color:#667c8b}}.statuschip{{display:inline-block;margin-top:.34rem;border-radius:999px;padding:.12rem .36rem;font-size:.54rem;font-weight:900;background:#edf3f7}}.complete .statuschip{{background:#eaf8f4;color:#08765f}}.ready .statuschip{{background:#fff0c2;color:#815900}}.workcard{{background:#fff;border:1px solid #d5e1e8;border-radius:14px;padding:.8rem;min-height:278px}}.worktitle{{font-size:1.08rem;font-weight:900;color:#17324a;margin:.25rem 0}}.workcheck{{display:grid;grid-template-columns:1fr auto;gap:.4rem;padding:.42rem .48rem;border-bottom:1px solid #e7eef2;font-size:.69rem}}.workcheck span{{color:#15836d;font-weight:900}}@media(max-width:1200px){{.networkstage{{grid-template-columns:1fr 70px .85fr 70px 1fr}}.flowstage small{{display:none}}}}@media(prefers-reduced-motion:reduce){{.datapacket,.controlhub .ring{{animation:none!important}}}}

/* Focused Agent Operations */
.agentprogress{{display:grid;grid-template-columns:repeat(5,1fr);gap:.42rem;margin:.55rem 0 .7rem}}.agentdot{{background:#fff;border:1px solid #d5e1e8;border-radius:11px;padding:.5rem .55rem;position:relative}}.agentdot:after{{content:'›';position:absolute;right:-.34rem;top:26px;color:#8dafbd;font-size:1rem;z-index:2}}.agentdot:last-child:after{{display:none}}.agentdot.complete{{border-bottom:4px solid #15836d}}.agentdot.active{{border-bottom:4px solid #f4ab00;background:#fff9e8}}.agentdot.waiting{{opacity:.58}}.agentdot .step{{font-size:.56rem;letter-spacing:.08em;color:#00a6b2;font-weight:900}}.agentdot b{{display:block;font-size:.69rem;margin-top:.12rem}}.agentdot span{{font-size:.56rem;color:#64798a}}.agentfocus{{display:grid;grid-template-columns:.92fr 1.35fr .84fr;gap:.8rem;align-items:stretch}}.focuscard{{background:#fff;border:1px solid #d5e1e8;border-radius:14px;padding:.78rem;box-shadow:0 5px 16px rgba(8,31,51,.05);min-height:292px}}.focuscard.active{{background:linear-gradient(150deg,#08283d,#0e6075);color:#fff;border:0}}.focuscard.active .eyebrow{{color:#72edf2}}.focuscard.active p{{color:#d4e8ef}}.focusagent{{font-size:1.25rem;font-weight:900;margin:.28rem 0 .4rem}}.focuscheck{{display:grid;grid-template-columns:1fr auto;gap:.4rem;padding:.42rem 0;border-bottom:1px solid rgba(120,150,165,.22);font-size:.69rem}}.focuscheck strong{{color:#43d7bd}}.transformflow{{display:grid;grid-template-columns:1fr 38px 1fr;gap:.42rem;align-items:stretch}}.recordbox{{background:#f4f8fa;border-radius:12px;padding:.68rem}}.recordbox.clean{{background:#eaf8f4}}.recordbox h4{{font-size:.72rem;margin:0 0 .45rem;color:#17324a}}.recordrow{{display:grid;grid-template-columns:.8fr 1.2fr;gap:.4rem;padding:.37rem 0;border-bottom:1px solid #dce7ec;font-size:.66rem}}.recordrow span:first-child{{color:#657b89}}.recordrow b{{text-align:right;color:#17324a}}.transformarrow{{display:flex;align-items:center;justify-content:center;color:#00a6b2;font-size:1.8rem;font-weight:900}}.finding{{padding:.5rem .55rem;border-radius:10px;background:#f3f7fa;margin:.38rem 0;font-size:.67rem}}.finding b{{display:block;color:#17324a;margin-bottom:.12rem}}.finding.alert{{background:#fff7e3;border-left:4px solid #f4ab00}}.microstats{{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem;margin:.45rem 0 .6rem}}.microstat{{background:#fff;border:1px solid #d5e1e8;border-radius:11px;padding:.48rem .58rem}}.microstat strong{{display:block;font-size:1.05rem;color:#0b2c43}}.microstat span{{font-size:.61rem;color:#64798a}}.agentactions{{display:grid;grid-template-columns:1.2fr .8fr;gap:.55rem;margin-top:.55rem}}@media(max-width:1200px){{.agentfocus{{grid-template-columns:.9fr 1.25fr}}.agentfocus .focuscard:last-child{{grid-column:1/-1;min-height:auto}}.agentdot span{{display:none}}}}

/* Treasury AI market context */
.marketgrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem;margin:.65rem 0}}.marketcard{{position:relative;background:#fff;border:1px solid #d5e1e8;border-radius:16px;padding:.9rem;min-height:210px;box-shadow:0 7px 20px rgba(8,31,51,.07);overflow:hidden}}.marketcard:before{{content:'';position:absolute;left:0;right:0;top:0;height:5px;background:#00a6b2}}.marketcard.maturity:before{{background:#f4ab00}}.marketcard.frontier:before{{background:#15836d}}.marketnum{{font-size:2.5rem;font-weight:900;line-height:1;color:#0b2c43;margin:.38rem 0 .25rem}}.marketcard h3{{font-size:1rem!important;margin:.18rem 0 .4rem!important}}.marketcard p{{font-size:.72rem;color:#526b7a;line-height:1.42}}.sourcekey{{font-size:.59rem;color:#758995;margin-top:.45rem}}.maturitybar{{background:#fff;border:1px solid #d5e1e8;border-radius:16px;padding:.8rem .9rem;margin:.55rem 0}}.maturitytrack{{display:grid;grid-template-columns:repeat(4,1fr);gap:.35rem;align-items:stretch;margin-top:.5rem}}.maturityphase{{position:relative;padding:.58rem .55rem;border-radius:10px;background:#edf3f7;border-top:4px solid #9eb4c0;min-height:92px}}.maturityphase.current{{background:#e8f7f8;border-top-color:#00a6b2}}.maturityphase.frontier{{background:#eaf8f4;border-top-color:#15836d;box-shadow:0 0 0 2px rgba(21,131,109,.12)}}.maturityphase b{{display:block;font-size:.72rem;color:#17324a}}.maturityphase span{{display:block;font-size:.6rem;color:#64798a;line-height:1.3;margin-top:.2rem}}.demomarker{{display:inline-block;margin-top:.35rem;padding:.12rem .38rem;border-radius:999px;background:#15836d;color:#fff;font-size:.55rem;font-weight:900}}.scopegrid{{display:grid;grid-template-columns:1fr 1fr;gap:.7rem;margin:.55rem 0}}.scopebox{{border-radius:13px;padding:.7rem .8rem;background:#eaf8f4;border-left:4px solid #15836d}}.scopebox.not{{background:#fff7e3;border-left-color:#f4ab00}}.scopebox b{{display:block;font-size:.76rem;color:#17324a;margin-bottom:.25rem}}.scopebox span{{display:block;font-size:.64rem;color:#536b77;line-height:1.45}}@media(max-width:1100px){{.marketgrid{{grid-template-columns:1fr}}.marketcard{{min-height:auto}}.maturitytrack{{grid-template-columns:1fr 1fr}}}}

/* Market context: projection-readable typography */
.marketcard{{padding:1rem 1.05rem;min-height:218px}}.marketnum{{font-size:2.85rem;margin:.42rem 0 .32rem}}.marketcard h3{{font-size:1.12rem!important;line-height:1.18!important;margin:.22rem 0 .48rem!important}}.marketcard p{{font-size:.82rem;line-height:1.48}}.sourcekey{{font-size:.68rem;margin-top:.55rem}}.maturitybar{{padding:.9rem 1rem}}.maturityphase{{padding:.68rem .66rem;min-height:104px}}.maturityphase b{{font-size:.84rem;line-height:1.15}}.maturityphase span{{font-size:.7rem;line-height:1.38;margin-top:.28rem}}.demomarker{{font-size:.63rem;padding:.15rem .42rem;margin-top:.42rem}}.scopebox{{padding:.8rem .9rem}}.scopebox b{{font-size:.86rem;margin-bottom:.32rem}}.scopebox span{{font-size:.72rem;line-height:1.5}}div[data-testid="stExpander"] summary p{{font-size:.84rem!important;font-weight:700!important}}div[data-testid="stExpanderDetails"] p{{font-size:.79rem!important;line-height:1.45!important}}

/* Collapsible presentation navigation */
button[kind="secondary"] p{{font-weight:800}}.st-key-show_navigation{{position:relative;z-index:20;margin-bottom:-.35rem}}.st-key-show_navigation button{{min-height:31px!important;font-size:.74rem!important;background:#0B2C43!important;color:#fff!important;border-color:#164D68!important}}.st-key-show_navigation button p{{color:#fff!important}}

/* Contrast correction and simplified operating thesis */
.demomarker{{color:#FFFFFF!important;background:#15836D!important;letter-spacing:.04em}}.maturityphase .demomarker{{color:#FFFFFF!important}}
.thesisclean{{display:grid;grid-template-columns:.9fr 1.18fr .9fr;gap:1rem;align-items:stretch;margin:.7rem 0 .55rem}}.thesisclean .cleanpanel{{background:#fff;border:1px solid #d5e1e8;border-radius:18px;padding:1rem;box-shadow:0 8px 22px rgba(8,31,51,.07);min-height:330px}}.cleanpanel.reality{{border-top:5px solid #f4ab00}}.cleanpanel.decision{{border-top:5px solid #15836d}}.cleanheadline{{font-size:1.18rem;font-weight:900;line-height:1.2;color:#17324a;margin:.42rem 0 .78rem}}.signalstrip{{display:grid;grid-template-columns:repeat(4,1fr);gap:.38rem;margin:.55rem 0 .8rem}}.signal{{background:#f3f7fa;border-radius:10px;padding:.52rem .25rem;text-align:center}}.signal strong{{display:block;font-size:1.25rem;color:#0b2c43}}.signal span{{font-size:.61rem;color:#64798a}}.constraint{{display:grid;grid-template-columns:22px 1fr;gap:.45rem;align-items:center;padding:.48rem 0;border-bottom:1px solid #e6edf1;font-size:.72rem}}.constraint i{{display:flex;width:21px;height:21px;align-items:center;justify-content:center;border-radius:50%;background:#fff0c2;color:#815900;font-style:normal;font-size:.65rem;font-weight:900}}
.cleanflow{{background:linear-gradient(155deg,#07283d,#0f647a);border-radius:20px;padding:1rem;color:#fff;box-shadow:0 16px 34px rgba(8,31,51,.18);min-height:330px}}.cleanflow .flowtitle{{font-size:1.06rem;font-weight:900;text-align:center;margin:.3rem 0 .75rem}}.cleanstep{{display:grid;grid-template-columns:34px 1fr;gap:.58rem;align-items:center;padding:.62rem;margin:.46rem 0;border-radius:12px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.18)}}.cleanstep .num{{display:flex;width:30px;height:30px;border-radius:50%;align-items:center;justify-content:center;background:#35d8de;color:#062637;font-weight:900;font-size:.75rem}}.cleanstep b{{display:block;font-size:.82rem}}.cleanstep span{{display:block;font-size:.65rem;color:#cfe5ec;margin-top:.12rem;line-height:1.3}}.cleangate{{margin-top:.65rem;padding:.65rem;border-radius:11px;text-align:center;border:1px solid rgba(255,224,138,.7);background:rgba(244,171,0,.14)}}.cleangate b{{display:block;font-size:.74rem}}.cleangate span{{display:block;color:#f7e9bd;font-size:.62rem;margin-top:.15rem}}.decisionlead{{font-size:.85rem;color:#526b78;line-height:1.45;margin-bottom:.6rem}}.decisionout{{padding:.7rem;margin:.5rem 0;border-radius:11px;background:#eaf8f4;border-left:4px solid #15836d}}.decisionout b{{display:block;font-size:.8rem;color:#17324a}}.decisionout span{{display:block;font-size:.65rem;color:#53706b;margin-top:.15rem}}.thesisquestion{{padding:.7rem .85rem;border-radius:12px;background:#fff7e3;border-left:4px solid #f4ab00;font-size:.82rem;margin:.55rem 0}}@media(max-width:1100px){{.thesisclean{{grid-template-columns:1fr}}.thesisclean .cleanpanel,.cleanflow{{min-height:auto}}}}
</style>''',unsafe_allow_html=True)

PAGES=['Title','Treasury AI in 2026','Treasury Team of One','Historical Baseline','Friday Snapshot','Organization Map','Monday Inbox','Agent Operations','Human Review','The Storm','Dilemma','Response Studio','CFO Brief','Audit & Downloads']
CLOCK={p:('Mon 8:00 AM',0,'Presentation ready') for p in PAGES}; CLOCK.update({'Historical Baseline':('Fri 4:20 PM',0,'Baseline preparation'),'Friday Snapshot':('Fri 4:30 PM',0,'Risk baseline approved'),'Monday Inbox':('Mon 8:03 AM',3,'New evidence arrives'),'Agent Operations':('Mon 8:08 AM',8,'Agents process files'),'Human Review':('Mon 8:15 AM',15,'Material judgments'),'The Storm':('Mon 8:28 AM',28,'Forecast deteriorates'),'Dilemma':('Mon 8:42 AM',42,'Decision required'),'Response Studio':('Mon 8:55 AM',55,'Responses tested'),'CFO Brief':('Mon 9:25 AM',85,'Brief ready'),'Audit & Downloads':('Mon 9:30 AM',90,'Briefing time')})
for k,v in {'page':0,'hist':None,'storm':0,'reviewed':0,'funding':0,'inspect':False,'audience_choice':'No action','presentation_mode':True,'agent_step':0,'files_pulled':0,'selected_file':0,'nav_hidden':False}.items(): st.session_state.setdefault(k,v)
def hero(k,t,s): st.markdown(f'<div class="hero"><div class="eyebrow">{k}</div><h1>{t}</h1><p>{s}</p></div>',unsafe_allow_html=True)
def money(v): return f'${abs(v)/1e6:.2f}M' if abs(v)>=1e6 else f'${abs(v):,.0f}'
def clock(page):
 t,e,phase=CLOCK[page]; rem=max(0,90-e); txt='Before Monday' if page in PAGES[2:4] else ('Briefing time' if rem==0 else f'{rem} min to CFO brief'); st.markdown(f'<div class="clockbar"><div><div class="clocklabel">Briefing Clock</div><div class="clocktime">{t}</div></div><div><div class="clocklabel">{phase}</div><div class="clocktrack"><div class="clockfill" style="width:{e/90*100:.0f}%"></div></div></div><div class="clockremain">{txt}</div></div>',unsafe_allow_html=True)
def fan(r,title,prior=None):
 f=go.Figure(); f.add_trace(go.Scatter(x=DATES,y=r['p975'],line_width=0,showlegend=False)); f.add_trace(go.Scatter(x=DATES,y=r['p025'],fill='tonexty',fillcolor='rgba(0,186,198,.11)',line_width=0,name='95% Range')); f.add_trace(go.Scatter(x=DATES,y=r['p75'],line_width=0,showlegend=False)); f.add_trace(go.Scatter(x=DATES,y=r['p25'],fill='tonexty',fillcolor='rgba(0,186,198,.24)',line_width=0,name='50% Range')); f.add_trace(go.Scatter(x=DATES,y=r['mean'],line=dict(color=C['cyan'],width=4),name='Current Expected'))
 if prior is not None:f.add_trace(go.Scatter(x=DATES,y=prior['mean'],line=dict(color='#7D8D99',dash='dot'),name='Friday Expected'))
 f.add_hline(y=MINIMUM,line_color=C['amber'],line_dash='dash'); f.add_hline(y=0,line_color=C['red']); f.update_layout(title=title,height=330,paper_bgcolor='white',plot_bgcolor='white',legend_orientation='h',margin=dict(l=15,r=10,t=38,b=10),yaxis_tickprefix='$',yaxis_tickformat=',.0f'); return f
def jump(label,target):
 if st.button(label,type='primary',use_container_width=True):st.session_state.page=target;st.rerun()
def find_attachment(name):
 for candidate in [INBOX/name,BASE/'data'/'monday_inbox'/name,BASE/name]:
  if candidate.exists(): return candidate
 return INBOX/name
def preview_file(name):
 path=find_attachment(name)
 if not path.exists(): return None
 try:
  return pd.read_csv(path) if path.suffix.lower()=='.csv' else pd.read_excel(path,engine='openpyxl')
 except Exception: return None
# Optional navigation drawer for presentation visibility
if st.session_state.nav_hidden:
 st.markdown('<style>[data-testid="stSidebar"]{display:none!important}.block-container{max-width:1700px!important}</style>',unsafe_allow_html=True)
 nav_left,nav_right=st.columns([8.6,1.4])
 with nav_right:
  if st.button('☰ Show Navigation',use_container_width=True,key='show_navigation'):
   st.session_state.nav_hidden=False;st.rerun()
with st.sidebar:
 st.markdown('## ◈ Treasury Agent Operations');st.caption('Evidence to Decision')
 if st.button('Hide Navigation',use_container_width=True,key='hide_navigation'):
  st.session_state.nav_hidden=True;st.rerun()
 st.session_state.presentation_mode=st.toggle('Presentation Mode',value=st.session_state.presentation_mode);st.markdown(f'**Act {st.session_state.page+1} of {len(PAGES)}**');st.caption(PAGES[st.session_state.page]);a,b=st.columns(2)
 if a.button('←',use_container_width=True):st.session_state.page=max(0,st.session_state.page-1);st.rerun()
 if b.button('→',use_container_width=True):st.session_state.page=min(len(PAGES)-1,st.session_state.page+1);st.rerun()
 if st.button('Reset Demo',use_container_width=True):
  for k,v in {'page':0,'storm':0,'reviewed':0,'funding':0,'inspect':False,'audience_choice':'No action','agent_step':0,'files_pulled':0,'selected_file':0,'nav_hidden':False}.items():st.session_state[k]=v
  st.rerun()
if st.session_state.hist is None:
 try:st.session_state.hist=load_history(SAMPLE)
 except Exception as e:st.error(str(e));st.stop()
hist=st.session_state.hist;friday=simulate(hist,-1);page=PAGES[st.session_state.page]
if page not in PAGES[:3]:clock(page)

if page=='Title':
 st.markdown('''<div class="titlehero"><div class="titlecopy"><div class="eyebrow">TAMPA BAY AFP &nbsp;|&nbsp; SAINT LEO UNIVERSITY &nbsp;|&nbsp; SEPTEMBER 11, 2026</div><h1>The Treasury Team of One</h1><h2>Building AI-Powered Financial Solutions</h2><p>From fragmented evidence to a governed liquidity decision</p><div><span class="casebadge">6 Entities</span><span class="casebadge">3 Currencies</span><span class="casebadge">8 Messages</span><span class="casebadge">10 Attachments</span><span class="casebadge deadlinebadge">1 CFO Deadline</span></div><div class="titlemeta">Zachary A. Smith, Ph.D.<br>Associate Professor of Economics and Finance | Saint Leo University<br><span style="color:#9FC5D3">Former Financial Advisor and Quantitative Analyst | Finance Educator and Researcher</span></div></div><div class="agentvisual"><div class="agentorbit"><span class="dataorb orb1"></span><span class="dataorb orb2"></span><span class="dataorb orb3"></span><span class="dataorb orb4"></span><span class="dataorb orb5"></span><div class="agentnode n1 source-agent">INBOX<br>AGENT</div><div class="agentnode n2 source-agent">VERSION<br>AGENT</div><div class="agentnode n3 transform-agent">DOCUMENT<br>AGENT</div><div class="agentnode n4 transform-agent">MAPPING<br>AGENT</div><div class="agentnode n5 risk-agent">RISK<br>AGENT</div><div class="agentnode n6 control-agent">CONTROL<br>AGENT</div></div><div class="agentcore">TREASURY<br>CONTROL<br>CENTER</div></div></div>''',unsafe_allow_html=True)
 st.markdown('<div class="openingquestion">Can One Treasury Professional Turn Fragmented Evidence Into a Decision Before 9:30?</div>',unsafe_allow_html=True);a,b=st.columns([1.35,1])
 with a:jump('Launch the Liquidity Simulation →',1)
 with b:
  with st.popover('View Case Brief',use_container_width=True):st.markdown('**The Challenge**\n\nSix entities, three currencies, eight messages, and ten attachments must become a defensible recommendation before a 9:30 CFO briefing.\n\n**The Demonstration**\n\nHistorical Risk → Monday Inbox → Agent Operations → Human Control → Liquidity Storm → Treasury Response → CFO Decision.')
elif page=='Treasury AI in 2026':
 hero('MARKET CONTEXT | AUGUST 2026','Treasury AI Is Real. Maturity Is Uneven. Agentic Orchestration Is Emerging.','This demonstration sits between today’s embedded AI capabilities and a more integrated, governed evidence-to-decision operating model.')
 st.markdown('''<div class="marketgrid"><div class="marketcard"><div class="eyebrow" style="color:#087f89">ADOPTION</div><div class="marketnum">74%</div><h3>Expanding or Actively Using AI</h3><p>PwC’s 2025 survey of 350 treasurers reports active or expanding AI use, particularly in machine learning and predictive analytics. Reported use areas include liquidity, exposure management, accounting, forecasting, anomaly detection, reconciliation, and data gathering.</p><div class="sourcekey">Source [1]</div></div><div class="marketcard maturity"><div class="eyebrow" style="color:#996500">MATURITY</div><div class="marketnum">26%</div><h3>Moderately or Very Mature</h3><p>The same survey reports that most organizations remain in pilot or early implementation stages: 42% piloting and 32% in early development or implementation.</p><div class="sourcekey">Source [1]</div></div><div class="marketcard frontier"><div class="eyebrow" style="color:#08765f">AGENTIC FRONTIER</div><div class="marketnum" style="font-size:1.65rem">Start Small</div><h3>Show the Work. Maintain Guardrails.</h3><p>AFP Boston 2025 commentary describes lean treasury teams exploring agentic AI through low-risk, repeatable pilots with clean context, validation, visible work, and non-negotiable guardrails.</p><div class="sourcekey">Source [2]</div></div></div>''',unsafe_allow_html=True)
 st.markdown('''<div class="maturitybar"><div class="eyebrow" style="color:#087f89">TREASURY AI MATURITY CONTINUUM</div><div class="maturitytrack"><div class="maturityphase current"><b>Embedded AI</b><span>Forecasting<br>Anomaly detection<br>Classification</span></div><div class="maturityphase current"><b>General Copilots</b><span>Summaries<br>Drafting<br>Analysis support</span></div><div class="maturityphase"><b>Bounded Agents</b><span>Retrieval<br>Reconciliation<br>Exception routing</span></div><div class="maturityphase frontier"><b>Integrated Workflow</b><span>Evidence to decision<br>Human control gate<br>Governed orchestration</span><span class="demomarker">THIS DEMONSTRATION</span></div></div></div>''',unsafe_allow_html=True)
 st.markdown('''<div class="scopegrid"><div class="scopebox"><b>What This Demonstration Shows</b><span>Inbox and attachment lineage · Version identification · Data interpretation and normalization · Exception detection · Human approval · Probabilistic liquidity analysis · Decision-brief preparation</span></div><div class="scopebox not"><b>What This Demonstration Does Not Claim</b><span>Autonomous payments · Autonomous borrowing or transfers · Production Outlook, ERP, TMS, or bank connectivity · Delegation of treasury accountability to AI</span></div></div>''',unsafe_allow_html=True)
 with st.expander('Sources and Methodology'):
  st.markdown('''**[1] PwC, 2025 Global Treasury Survey**  
Published June 25, 2025. Survey of 350 treasurers globally. Findings used here: 74% expanding or actively using AI; 26% moderately or very mature; 42% piloting; 32% in early development or implementation.  
[Read the PwC 2025 Global Treasury Survey](https://www.pwc.com/us/en/services/consulting/finance-accounting-transformation/library/2025-global-treasury-survey.html)

**[2] ION Treasury, Tokens, AI Agents, and Uncertainty: The Real Talk from AFP Boston 2025**  
Published April 14, 2026. The discussion emphasizes lean treasury teams, low-risk repeatable pilots, clean context, validation, visible work, and guardrails.  
[Review the AFP Boston 2025 Treasury Discussion](https://iongroup.com/podcasts/treasury/tokens-ai-agents-and-uncertainty-the-real-talk-from-afp-boston-2025/)

**[3] EACT Treasury Survey 2025**  
The survey identifies cash-flow forecasting as a leading treasury priority and cautions that fragmented systems, manual processes, and limited standardization constrain advanced technology adoption.  
[Review the EACT Treasury Survey 2025](https://admin.treasury-management.com/wp-content/uploads/2025/05/EACT_survey_2025-final.pdf)

*Interpretive note:* The maturity continuum is a presentation framework created for this demonstration. It is not a scale published by the cited sources.''')
 jump('See the Operating Model →',2)
elif page=='Treasury Team of One':
 hero('ACT 1 | THE OPERATING THESIS','From Fragmented Evidence to a Defensible Treasury Decision.','Agents expand analytical capacity. Treasury retains authority over material judgments and actions.')
 st.markdown('''<div class="thesisclean"><div class="cleanpanel reality"><div class="eyebrow" style="color:#996500">MONDAY REALITY</div><div class="cleanheadline">One analyst faces more evidence than can be reconciled manually before the briefing.</div><div class="signalstrip"><div class="signal"><strong>8</strong><span>Messages</span></div><div class="signal"><strong>10</strong><span>Files</span></div><div class="signal"><strong>6</strong><span>Entities</span></div><div class="signal"><strong>3</strong><span>Currencies</span></div></div><div class="constraint"><i>!</i><span>Versions and email context conflict</span></div><div class="constraint"><i>!</i><span>Cash availability differs from reported cash</span></div><div class="constraint"><i>9:30</i><span>The decision window is closing</span></div></div><div class="cleanflow"><div class="eyebrow" style="text-align:center">AGENTIC TREASURY WORK</div><div class="flowtitle">Capacity expands. Accountability stays with treasury.</div><div class="cleanstep"><span class="num">1</span><div><b>Collect and Read</b><span>Retrieve messages, files, versions, structures, and context.</span></div></div><div class="cleanstep"><span class="num">2</span><div><b>Reconcile and Quantify</b><span>Normalize records, surface exceptions, and measure liquidity risk.</span></div></div><div class="cleanstep"><span class="num">3</span><div><b>Propose and Explain</b><span>Prepare treatments, response options, and an evidence-linked brief.</span></div></div><div class="cleangate"><b>HUMAN CONTROL GATE</b><span>Treasury approves material corrections, funding actions, and communication.</span></div></div><div class="cleanpanel decision"><div class="eyebrow" style="color:#08765f">DECISION SYSTEM</div><div class="cleanheadline">The output is not another dashboard. It is a controlled decision path.</div><p class="decisionlead">Each conclusion remains connected to the evidence and approval that produced it.</p><div class="decisionout"><b>Approved Evidence</b><span>One review-ready truth set</span></div><div class="decisionout"><b>Quantified Exposure</b><span>One probabilistic liquidity view</span></div><div class="decisionout"><b>Actionable Recommendation</b><span>One response and one CFO brief</span></div></div></div>''',unsafe_allow_html=True)
 st.markdown('<div class="thesisquestion"><b>The question for today:</b> Can agents expand treasury capacity without surrendering treasury control?</div>',unsafe_allow_html=True)
 jump('Establish the Friday Risk Baseline →',3)
elif page=='Historical Baseline':
 hero('T−2 | BEFORE MONDAY','Historical Forecast Performance Loaded','The Risk Agent reads the versioned historical-error file automatically.');a,b,c=st.columns(3);a.metric('Observations',len(hist));b.metric('Beginning',hist.date.min().strftime('%b %Y'));c.metric('Ending',hist.date.max().strftime('%b %Y'));st.dataframe(hist.head(6),use_container_width=True,hide_index=True,height=220);jump('Build the Friday Risk Baseline →',4)
elif page=='Friday Snapshot':
 hero('T−1 | FRIDAY','A Manageable 95% Baseline','The analyst enters the weekend with measured liquidity risk.');l,r=st.columns([2.2,1]);l.plotly_chart(fan(friday,'Friday Cash Distribution'),use_container_width=True)
 with r:a,b=st.columns(2);a.metric('VaR 95%',money(friday['var']));b.metric('CVaR 95%',money(friday['cvar']));c,d=st.columns(2);c.metric('P(Below $200K)',f"{friday['pmin']:.1%}");d.metric('P(Negative)',f"{friday['pneg']:.1%}");jump('Meet Meridian Components →',5)
elif page=='Organization Map':
 hero('ORGANIZATIONAL CONTEXT','A Distributed Business. One Treasury Control Point.','Each entity contributes a different piece of the liquidity picture. Central treasury preserves source context and creates one governed view.')
 st.markdown('''<div class="networkstage"><div class="entitycolumn"><div class="entitycard"><b>Meridian Holdings</b><div class="meta">Corporate Controller · USD · Parent</div><span class="datachip">Balances</span><span class="datachip">Central Revolver</span></div><div class="entitycard"><b>Meridian Manufacturing</b><div class="meta">Manufacturing Finance · USD · Core</div><span class="datachip">Weekly Forecast</span><span class="datachip">Payroll Note</span></div><div class="entitycard acquired"><b>Apex Distribution</b><div class="meta">Shared Services · USD · Acquired</div><span class="datachip">AP Schedule</span><span class="datachip">Payroll</span></div></div><div class="lane inbound"><span class="datapacket p1"></span><span class="datapacket p2"></span><span class="datapacket p3"></span></div><div class="controlhub"><div class="ring"></div><div class="eyebrow">CENTRAL CONTROL</div><strong>Treasury Team of One</strong><span>Inbox Agent<br>Human Control Gate<br>Liquidity Risk Engine</span></div><div class="lane outbound"><span class="datapacket p1"></span><span class="datapacket p2"></span><span class="datapacket p3"></span></div><div class="entitycolumn"><div class="entitycard acquired"><b>Gulf Components</b><div class="meta">Acquisition Controller + AR · USD</div><span class="datachip">Revised Forecast</span><span class="datachip">Orion Receipt</span></div><div class="entitycard global"><b>Meridian Canada</b><div class="meta">Canada Controller · CAD</div><span class="datachip">Local Forecast</span><span class="datachip">FX Assumption</span></div><div class="entitycard global"><b>Meridian Europe</b><div class="meta">Europe Controller · EUR</div><span class="datachip">Forecast</span><span class="datachip">Restricted Reserve</span></div></div></div><div class="netstats"><div class="netstat"><strong>8</strong><span>Messages</span></div><div class="netstat"><strong>10</strong><span>Attachments</span></div><div class="netstat"><strong>3</strong><span>Currencies</span></div><div class="netstat"><strong>0</strong><span>Common Schemas</span></div></div>''',unsafe_allow_html=True)
 jump('Open the Monday Inbox →',6)
elif page=='Monday Inbox':
 hero('T0 | MONDAY 8:03 AM','The Inbox Agent Pulls Current Evidence','Manually advance the Inbox Agent through the mailbox. Each click retrieves one message and its attachments into the controlled intake queue.')
 inbox=json.loads(INBOX_JSON.read_text())
 attachment_rows=[]
 for message_index,message in enumerate(inbox):
  for attachment in message['attachments']:
   attachment_rows.append({'Time':message['time'],'Sender':message['sender'],'Entity':message['entity'],'Subject':message['subject'],'Attachment':attachment,'Message Index':message_index})
 pulled=min(st.session_state.files_pulled,len(attachment_rows))
 left,right=st.columns([1.65,1],gap='large')
 with left:
  register=[]
  for idx,row in enumerate(attachment_rows):
   state='PULLED' if idx<pulled else ('NEXT' if idx==pulled else 'WAITING')
   register.append([row['Time'],row['Sender'],row['Entity'],row['Attachment'],state])
  st.dataframe(pd.DataFrame(register,columns=['Time','Sender','Entity','Attachment','State']),use_container_width=True,hide_index=True,height=330)
 with right:
  st.metric('Messages Scanned',len(inbox));st.metric('Attachments Pulled',f'{pulled}/{len(attachment_rows)}');st.metric('Intake Queue',pulled)
  if pulled<len(attachment_rows):
   nxt=attachment_rows[pulled]
   st.markdown(f'<div class="panel"><div class="eyebrow">NEXT RETRIEVAL</div><h3>{nxt["Attachment"]}</h3><p><b>Sender:</b> {nxt["Sender"]}<br><b>Entity:</b> {nxt["Entity"]}<br><b>Subject:</b> {nxt["Subject"]}</p></div>',unsafe_allow_html=True)
   if st.button('Pull the Next Attachment →',type='primary',use_container_width=True):st.session_state.files_pulled+=1;st.rerun()
   if st.button('Pull All Remaining Attachments',use_container_width=True):st.session_state.files_pulled=len(attachment_rows);st.rerun()
  else:
   st.markdown('<div class="success"><b>Inbox retrieval complete:</b> Ten attachments and their email context are now available to the wrangling agents.</div>',unsafe_allow_html=True)
   jump('Begin Data Wrangling →',7)
elif page=='Agent Operations':
 if st.session_state.files_pulled < 10:
  hero('AGENT RUN 08-A','Complete the Inbox Retrieval First','The wrangling agents can only process evidence the Inbox Agent has placed in the controlled queue.')
  st.warning(f"{st.session_state.files_pulled} of 10 attachments have been retrieved.")
  jump('Return to the Monday Inbox →',6)
  st.stop()
 hero('AGENT RUN 08-A','One File. One Active Agent. One Visible Transformation.','Advance the selected evidence through the wrangling pipeline without losing the source context.')
 files=['Holdings_Balances.csv','Mfg_Weekly_View.xlsx','Gulf_Cash_Fcst.xlsx','Gulf_Cash_Fcst_v2.xlsx','Apex_Disbursements.csv','Canada_CAD.xlsx','Europe_EUR.xlsx','Europe_Reserve.csv','Facilities.xlsx','AR_Expectations.xlsx']
 selected=st.selectbox('Evidence in Focus',files,index=min(st.session_state.selected_file,len(files)-1),label_visibility='collapsed')
 st.session_state.selected_file=files.index(selected)
 stages=[('Document Agent','Structure'),('Version Agent','Version'),('Mapping Agent','Normalize'),('Reconciliation Agent','Controls'),('Risk Agent','Assumption')]
 completed=min(st.session_state.agent_step,len(stages))
 active_idx=min(completed,len(stages)-1)
 active_agent,active_label=stages[active_idx]
 rail=[]
 for idx,(agent,label) in enumerate(stages):
  state='complete' if idx<completed else ('active' if idx==completed else 'waiting')
  rail.append(f'<div class="agentdot {state}"><div class="step">STEP {idx+1}</div><b>{agent}</b><span>{label}</span></div>')
 st.markdown('<div class="agentprogress">'+''.join(rail)+'</div>',unsafe_allow_html=True)
 st.markdown(f'<div class="microstats"><div class="microstat"><strong>10</strong><span>Files Retrieved</span></div><div class="microstat"><strong>{completed}/5</strong><span>Stages Complete</span></div><div class="microstat"><strong>{6 if completed>=4 else 0}</strong><span>Material Exceptions</span></div></div>',unsafe_allow_html=True)
 checks={
  'Document Agent':['Workbook structure read','Headers and dates detected','Notes captured'],
  'Version Agent':['Filename compared','Email instruction matched','Current version proposed'],
  'Mapping Agent':['Entity alias normalized','Currency standardized','Dates and signs aligned'],
  'Reconciliation Agent':['Duplicates tested','Restrictions checked','Facility math recalculated'],
  'Risk Agent':['Approved evidence isolated','Model parameter identified','Assumption ledger prepared']}
 raw_values={'Holdings_Balances.csv':[('Entity','MERIDIAN HOLDINGS'),('Account','100442'),('Currency','US$'),('Balance','2450000')],
  'Gulf_Cash_Fcst.xlsx':[('Entity','Gulf Comp.'),('Day','Wed'),('Cash In','620000'),('Note','Confirmation pending')],
  'Gulf_Cash_Fcst_v2.xlsx':[('Entity','Gulf Comp.'),('Day','Wed'),('Cash In','620000'),('Version','v2')],
  'AR_Expectations.xlsx':[('Customer','Orion Auto'),('Invoice','8812'),('Expected','9/2/26'),('Amount','620000')]}
 raw=raw_values.get(selected,[('File',selected),('Structure','Source-specific'),('Context','Email preserved'),('Status','Retrieved')])
 clean=[('Entity','Gulf Components' if 'Gulf' in selected or 'AR_' in selected else 'Canonicalized'),('Currency','USD'),('Dates','Normalized'),('Status','Review Ready')]
 raw_html=''.join(f'<div class="recordrow"><span>{k}</span><b>{v}</b></div>' for k,v in raw)
 clean_html=''.join(f'<div class="recordrow"><span>{k}</span><b>{v}</b></div>' for k,v in clean)
 check_html=''.join(f'<div class="focuscheck"><span>{item}</span><strong>✓</strong></div>' for item in checks[active_agent])
 st.markdown(f'''<div class="agentfocus"><div class="focuscard active"><div class="eyebrow">ACTIVE AGENT</div><div class="focusagent">{active_agent}</div><p>{dict(stages)[active_agent]} work is being applied to <b>{selected}</b>.</p>{check_html}</div><div class="focuscard"><div class="eyebrow" style="color:#087f89">VISIBLE TRANSFORMATION</div><div class="transformflow"><div class="recordbox"><h4>RAW EVIDENCE</h4>{raw_html}</div><div class="transformarrow">→</div><div class="recordbox clean"><h4>PROPOSED RECORD</h4>{clean_html}</div></div></div><div class="focuscard"><div class="eyebrow" style="color:#087f89">AGENT FINDINGS</div><div class="finding"><b>Source Lineage Preserved</b>Email, attachment, and source entity remain linked.</div><div class="finding"><b>Confidence</b>{'96%' if completed>=3 else 'Pending current stage'}</div><div class="finding alert"><b>Human Review Trigger</b>{'Material exception identified' if completed>=4 else 'No material decision released yet'}</div></div></div>''',unsafe_allow_html=True)
 with st.expander('Inspect the Source File'):
  preview=preview_file(selected)
  if preview is not None:st.dataframe(preview.head(10),use_container_width=True,hide_index=True,height=230)
  else:st.warning('The source file could not be previewed.')
 a,b=st.columns([1.2,.8])
 if completed<len(stages):
  if a.button('Run the Next Agent Step →',type='primary',use_container_width=True):st.session_state.agent_step+=1;st.rerun()
  if b.button('Complete the Pipeline',use_container_width=True):st.session_state.agent_step=len(stages);st.rerun()
 else:
  st.markdown('<div class="success"><b>Wrangling complete:</b> The material exceptions are ready for treasury review.</div>',unsafe_allow_html=True)
  jump('Open the Human Control Gate →',8)
elif page=='Human Review':
 hero('HUMAN CONTROL GATE','Agents Propose. Treasury Decides.','Inspect the actual source context and rows before approving a material treatment.')
 evidence=[
  {'issue':'Duplicate Holdings Balance','impact':'$2.45M possible overstatement','proposal':'Retain one canonical record and quarantine the duplicate','entity':'Meridian Holdings','sender':'Corporate Controller','subject':'Friday balances, revised file may follow','file':'Holdings_Balances.csv','raw':'Accounts 00100442 and 100442 carry the same $2.45 million balance.','finding':'Likely duplicate after restoring the leading zero and matching the entity alias.','confidence':'98%'},
  {'issue':'Reserve Unit Anomaly','impact':'Material available-cash overstatement','proposal':'Interpret as EUR 425K after review and exclude as restricted','entity':'Meridian Europe','sender':'Europe Controller','subject':'Forecast and restricted reserve','file':'Europe_Reserve.csv','raw':'Account EU7799 reports 42,500,000 and Restricted = Y.','finding':'Likely cents-versus-units anomaly; the balance cannot be swept.','confidence':'94%'},
  {'issue':'Orion Timing','impact':'$620K timing dependency','proposal':'Retain one receivable and model settlement probabilistically','entity':'Gulf Components','sender':'AR Operations','subject':'Orion timing remains unconfirmed','file':'AR_Expectations.xlsx','raw':'INV-8812 appears twice; expected September 2; average delay is five days.','finding':'Duplicate receivable candidate and optimistic settlement date.','confidence':'96%'},
  {'issue':'Duplicate Payroll','impact':'$245K possible outflow duplication','proposal':'Retain one verified payment','entity':'Gulf Components','sender':'Shared Services','subject':'AP and payroll schedule','file':'Apex_Disbursements.csv','raw':'Gulf payroll of $245,000 appears under two entity aliases.','finding':'Potential duplicate payroll record.','confidence':'97%'},
  {'issue':'Facility Mismatch','impact':'$50K liquidity overstatement','proposal':'Use commitment less drawn: $50K available','entity':'Gulf Components','sender':'Bank Partner','subject':'Facility availability','file':'Facilities.xlsx','raw':'Commitment $500K; drawn $450K; reported availability $100K.','finding':'Reconciled availability is $50K.','confidence':'100%'},
  {'issue':'FX Inconsistencies','impact':'Translation variance','proposal':'Use the approved treasury rate','entity':'Meridian Canada','sender':'Canada Controller','subject':'CAD forecast using Friday FX','file':'Canada_CAD.xlsx','raw':'The entity forecast uses conversion rate 0.742.','finding':'The local rate requires comparison with the approved treasury feed.','confidence':'91%'}]
i=min(st.session_state.reviewed, len(evidence) - 1)
e=evidence[i]
 st.markdown(f'<div class="panel"><div class="eyebrow">REVIEW {i+1} OF 6</div><h3>{e["issue"]}</h3><p><b>Potential Impact:</b> {e["impact"]}<br><b>Agent Proposal:</b> {e["proposal"]}</p></div>',unsafe_allow_html=True)
 a,b,c=st.columns(3)
 if a.button('Accept',type='primary',use_container_width=True):st.session_state.reviewed=min(6,i+1);st.session_state.inspect=False;st.rerun()
 if b.button('Defer',use_container_width=True):st.session_state.reviewed=min(6,i+1);st.session_state.inspect=False;st.rerun()
 if c.button('Inspect Evidence',use_container_width=True):st.session_state.inspect=not st.session_state.inspect;st.rerun()
 if st.session_state.inspect:
  left,right=st.columns([1,1.2],gap='large')
  with left:st.markdown(f'<div class="panel" style="border-left:4px solid #00BAC6"><div class="eyebrow">SOURCE CONTEXT</div><div class="row"><b>Entity</b><span class="grow"></span>{e["entity"]}</div><div class="row"><b>Sender</b><span class="grow"></span>{e["sender"]}</div><div class="row"><b>Email</b><span class="grow"></span>{e["subject"]}</div><div class="row"><b>Attachment</b><span class="grow"></span>{e["file"]}</div><p><b>Raw Evidence</b><br>{e["raw"]}</p><p><b>Agent Finding</b><br>{e["finding"]}</p><p><b>Confidence:</b> {e["confidence"]}</p></div>',unsafe_allow_html=True)
  with right:
   st.markdown('### Attachment Preview')
   preview=preview_file(e['file'])
   if preview is not None:st.dataframe(preview.head(10),use_container_width=True,hide_index=True,height=255)
   else:st.warning(f'Attachment not found: {e["file"]}')
 approved=st.session_state.reviewed;h1,h2=st.columns(2);h1.metric('Approved for Model',approved);h2.metric('Unresolved',max(0,6-approved));st.progress(approved/6)
 if approved>=4:jump('Release the Approved Truth Set →',9)
elif page=='The Storm':
 stage=st.session_state.storm;r=simulate(hist,stage);hero(f'STORM {stage+1} OF 5',STORMS[stage][0],'New evidence changes the assumptions behind Friday’s forecast.');l,rgt=st.columns([2.1,1]);l.plotly_chart(fan(r,'Friday Baseline vs. Current Risk',friday),use_container_width=True)
 with rgt:st.metric('VaR 95%',money(r['var']));st.metric('CVaR 95%',money(r['cvar']));st.metric('P(Negative)',f"{r['pneg']:.1%}");st.markdown(f'<div class="panel"><div class="eyebrow">EVIDENCE CAUSING THE MOVE</div><h3>{STORMS[stage][0]}</h3><p>The approved evidence changes expected cash, uncertainty, funding capacity, or accessibility.</p></div>',unsafe_allow_html=True)
 if stage<4:
  if st.button('Release the Next Event →',type='primary',use_container_width=True):st.session_state.storm+=1;st.rerun()
 else:jump('Reveal the Liquidity Dilemma →',10)
elif page=='Dilemma':
 hero('AUDIENCE DECISION','What Would You Recommend Before the 9:30 Briefing?','Choose a response before viewing the modeled result.');opts=['Rely on Receipt','Local Line','Intercompany Transfer','Layered Response'];cols=st.columns(4)
 for col,opt in zip(cols,opts):
  if col.button(opt,use_container_width=True):st.session_state.audience_choice=opt;st.rerun()
 st.markdown(f'<div class="warn"><b>Audience Recommendation:</b> {st.session_state.audience_choice}</div>',unsafe_allow_html=True);jump('Test the Audience Recommendation →',11)
elif page=='Response Studio':
 fmap={'No action':0,'Rely on Receipt':0,'Local Line':50000,'Intercompany Transfer':500000,'Layered Response':550000};f=fmap.get(st.session_state.audience_choice,0);st.session_state.funding=f;r=simulate(hist,4,funding=f);hero('RESPONSE STUDIO',f'Testing: {st.session_state.audience_choice}','The model reruns the tail-risk distribution.');l,rgt=st.columns([2.1,1]);l.plotly_chart(fan(r,'Post-Response Distribution',friday),use_container_width=True);rgt.metric('Funding',money(f));rgt.metric('P(Negative)',f"{r['pneg']:.1%}");rgt.dataframe(compare_responses(hist),use_container_width=True,hide_index=True,height=200);jump('Create the CFO Decision Brief →',12)
elif page=='CFO Brief':
 r=simulate(hist,4,funding=st.session_state.funding);hero('9:25 AM','A Governed Liquidity Decision','The conclusion remains traceable to source evidence.');st.markdown(f'<div class="panel"><h3>Gulf Components Liquidity Exposure</h3><p><b>Situation:</b> P(Negative) is {r["pneg"]:.1%}; expected tail shortfall is {money(r["cvar"])}.</p><p><b>Selected Response:</b> {st.session_state.audience_choice}, {money(st.session_state.funding)}.</p><p><b>Decision:</b> Confirm receipt timing and approve funding before the trough.</p></div>',unsafe_allow_html=True);jump('Open Audit & Outputs →',13)
else:
 hero('9:30 AM','From Fragmented Evidence to a Controlled Decision','Source traceability, agent speed, human judgment, and probabilistic response.');a,b,c=st.columns(3);a.metric('Messages Connected',9);b.metric('Attachments Processed',11);c.metric('Material Exceptions',7);st.markdown('<div class="success"><b>Friday’s model was not wrong. Monday’s evidence changed the assumptions. The advantage was the ability to adapt before uncertainty became a liquidity crisis.</b></div>',unsafe_allow_html=True);r=simulate(hist,4,funding=st.session_state.funding);out=pd.DataFrame({'date':DATES,'expected_cash':r['mean'],'p2_5':r['p025'],'p97_5':r['p975']});mem=io.BytesIO()
 with zipfile.ZipFile(mem,'w',zipfile.ZIP_DEFLATED) as z:z.writestr('forecast_percentiles.csv',out.to_csv(index=False));z.writestr('response_comparison.csv',compare_responses(hist).to_csv(index=False));z.writestr('attachment_profile.csv',process_inbox(INBOX).to_csv(index=False))
 st.download_button('Download Decision Package',mem.getvalue(),file_name='Treasury_Agent_Outputs.zip',type='primary',use_container_width=True)
